### ISSUE TITLE
Filter all the words in the world

### ISSUE THREAD

**Issue by iWader** [afolson/irl#3]

**Comment by afolson** [comment]
You know not what you ask of me. A task such as this takes careful planning and execution.
- [ ] Apply long broad-masked glines
- [ ] Open up my mIRC and set some brand new spamfilters
- [ ] Get in and own that skiddie
- [ ] Upon /whois, own that skiddie
- [ ] Bust a filter like I'm 'sposed to
- [ ] Approach girls and woo them with my oline
- [ ] Banhammer girls
- [ ] Suspend those who oppose me and their friends
- [ ] They don't know me, so kindly inform them to keep my name out of their foodholes

**Comment by iWader** [comment]
If this was bitbucket i'd approve this issue

**Comment by afolson** [comment]
16:28:56 [SwiftIRC] F cpnNPqt warn 0 918634 86400 It_dont_matter_who_you_is_miss_you_can_get_the_gline_HAAAAAAAAAA zomg!zomg@administrator.swiftirc.net entire alphabet
